### PR TITLE
A *little* update

### PR DESCRIPTION
**Pull request by dulacp**
Hey guys, here is a little update of the buildpack to follow the current modifications made on the original heroku repo.

I've made the merge and resolved the conflicts.

It's kind of big ^^ but I've only made the last 3 commits, the other ones are from the original repo.

### CODE REVIEW

**Comment by ondrowan** [comment]
+1, this fork is the only usable geodjango buildpack right now

**Comment by woodardj** [comment]
Bump.

**Comment by dulacp** [comment]
Little update to follow the improvements made by the original buildpack. The changes should not break anything, but I didn't test it yet so please if it does let me know.

**Comment by ondrowan** [comment]
That last commit broke the buildpack again. I just spent good part of afternoon debugging it. It works alright for existing apps, new ones are however broken. This error is occuring:

```
...
-----> Fetching and installing GEOS 3.3.2
-----> Installing ...
mv: cannot move `geos' to `/app/tmp/repo.git/.cache/geos': No such file or directory
```

There seems to be something fishy going on with `$CACHE_DIR`.

**Comment by dulacp** [comment]
Hey @ondrowan, you are right existing application are running fine... I know that kennethreitz made some modifications on the original heroku buildpack, we'll need to check what I missed.

**Comment by ondrowan** [comment]
Just to clarify for anyone that's in dire need of this buildpack for new app right now, you need to use following `BUILDPACK_URL` (for now):

`http://github.com/dulaccc/heroku-buildpack-geodjango/#3c4c08cf7cfed66db1c17dc8e996021c7435dfff`

**Comment by dulacp** [comment]
As I was refactoring the whole buildpack (like you can see right above my comment..) I found out that you can actually use the [heroku-geo-buildpack](https://github.com/cyberdelia/heroku-geo-buildpack#usage) and combine it with any other buildpack you want thanks to the [multi-buildpack](https://github.com/ddollar/heroku-buildpack-multi).
Check the [usage](https://github.com/cyberdelia/heroku-geo-buildpack#usage) for more details.

Cheers

**Comment by dulacp** [comment]
Too happy too soon concerning the `multi-buildpack`, can't make it work... so back to my own repository ^^

---

[`heroku-buildpack-geodjango`](https://github.com/dulaccc/heroku-buildpack-geodjango), a working heroku geodjango buildpack.

---

I've tested on new apps and it's working very well, I've updated the [Readme](https://github.com/dulaccc/heroku-buildpack-geodjango/blob/master/Readme.md) to reflect the changes brought to the repo.

Hope it will help others !

**Comment by aboutaaron** [comment]
@dulaccc hey, sorry we've been quiet on this. We've been researching better ways to deploy our apps to both Heroku and AWS. 

I haven't had a chance to test your buildpack modifications, but it looks like it's working. I'll check to make sure we can deploy stuff on it and if all is well, we'll go ahead and merge this in. Are there any other lingering issues you've noticed? Thanks to you and @ondrowan for working on this!

**Comment by dulacp** [comment]
Hi @aboutaaron, no other issue detected on my side, I'm using this buildpack fork on production and it's working like a charm :)

**Comment by jpmckinney** [comment]
I can confirm that @dulaccc's buildpack works. When I used this buildpack, I just got `code=H10 desc="App crashed"` errors.

**Comment by jpmckinney** [comment]
@dulaccc Does this pull request mean cirlabs and your fork are identical or are there other commits in your fork?

**Comment by dulacp** [comment]
@jpmckinney my fork is now identical thanks to @aboutaaron merge :)

**Pull request merged**
